name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Deploy GitHub pages
        run: npm run deploy
